"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from pybullet_utils.bullet_client import BulletClient

"""
This type stub file was generated by pyright.
"""
@dataclass(frozen=True)
class DisableRendering:
    sim: BulletClient
    def __enter__(self):
        ...
    
    def __exit__(self, *_):
        ...
    


