"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
class RedirectStream:
    def __init__(self, stream=..., file=...) -> None:
        ...
    
    def __enter__(self):
        ...
    
    def __exit__(self, *_):
        ...
    


