"""
This type stub file was generated by pyright.
"""

from typing import List, Tuple, Union

"""
This type stub file was generated by pyright.
"""
Vector3 = Union[Tuple[float, float, float], List[float]]
Vector4 = Union[Tuple[float, float, float, float], List[float]]
Position = Vector3
XYZWQuaternion = Vector4
WXYZQuaternion = Vector4
